name: Transform Figma Tokens to Chakra tokens

# events
on:
  push:
    branches:
      - 'main'
    paths:
      - 'figmaTokensChakra/**'

# jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js Env
        uses: actions/setup-node@v2.4.0

      - name: Checkout
        uses: actions/checkout@master

      # Install Dependencies
      - run: yarn install

      # Transform to Chakra tokens with SD
      - run: yarn run transform2CSS

      # copy needed files for the documentation components this can be improved
      - run: yarn copy-tokens

      # update dist to be consumed by framer
      - run: yarn run build

      # Give write access to repo
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built new version ready to be consumed by framer

      - name: purge jsdeliver
        run: |
          curl -X POST \
             http://purge.jsdelivr.net/ \
            -H 'cache-control: no-cache' \
            -H 'content-type: application/json' \
            -d '{
              "path": [
                "gh/esthercheran/chakraPOC@main/dist/index.js",
                "gh/esthercheran/chakraPOC@main/dist/Avatar.js",
                "gh/esthercheran/chakraPOC@main/dist/Button.js",
                "gh/esthercheran/chakraPOC@main/dist/Checkbox.js",
                "gh/esthercheran/chakraPOC@main/dist/Documentation.js",
                "gh/esthercheran/chakraPOC@main/dist/figmaTokens.js",
                "gh/esthercheran/chakraPOC@main/dist/Heading.js",
                "gh/esthercheran/chakraPOC@main/dist/IconButton.js",
                "gh/esthercheran/chakraPOC@main/dist/Image.js",
                "gh/esthercheran/chakraPOC@main/dist/Switch.js",
                "gh/esthercheran/chakraPOC@main/dist/Tag.js",
                "gh/esthercheran/chakraPOC@main/dist/documentationTokens/dark.js",
                "gh/esthercheran/chakraPOC@main/dist/documentationTokens/light.js",
              ]
            }'
